services:
  app:
    build: .
    container_name: hestia
    env_file:
      - .env
    ports:                # publish port ra host để Nginx host truy cập
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge